### ISSUE TITLE
Tool crashes even with a full RW PAT for 'list-teams' call

### ISSUE THREAD

**Issue by riyazwalikar** [EISMGard/github-audit-tool#2]
The following exception is raised when running the tool, even with a full RW token.

```bash
github.GithubException.GithubException: 403 {"message": "Resource not accessible by personal access token", "documentation_url": "https://docs.github.com/rest/reference/teams#list-teams"}
```

Tried this with multiple tokens.

**Comment by bfrancom** [comment]
These are the rights I've granted to my PAT that I tested today with:
`read:enterprise, read:org, read:repo_hook, repo, user`
Are you trying this against an organization, or personal account? Currently, it only works with an org.

**Comment by bfrancom** [comment]
@riyazwalikar Did you see my last comment, and any luck getting it working?
